"use client";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { CssBaseline, ThemeProvider } from "@mui/material";
import { theme } from "@/theme";
import { AuthProvider } from "@/providers/AuthProvider";
import { ProductHeader, ProductSideBar } from "@/components/ProductComponents";
import { Stack } from "@mui/material";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { PropsWithChildren } from "react";
import { usePathname } from "next/navigation";
// import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline>
        <AuthProvider>
          <ProductHeader />
          <Stack direction="row">
            <ProductSideBar />
            {children}
          </Stack>
        </AuthProvider>
      </CssBaseline>
    </ThemeProvider>
  );
}
