"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { CssBaseline, ThemeProvider } from "@mui/material";
import { theme } from "@/theme";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Userprovider } from "@/providers/UserProvider";
import { AuthProvider } from "@/providers/AuthProvider";
import { AddProductProvider } from "@/providers/AddproductProvider";
import { Footer, WholeHeader } from "@/components/userComponents";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Userprovider>
            <CssBaseline>
              <AddProductProvider>
                <WholeHeader />
                {/* <ThemeProvider theme={theme}> */}
                {children}
                <Footer />
              </AddProductProvider>
            </CssBaseline>
            <ToastContainer />
          </Userprovider>
        </AuthProvider>

        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
