"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { CssBaseline, ThemeProvider } from "@mui/material";
import { theme } from "@/theme";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Userprovider } from "@/providers/UserProvider";
import { AuthProvider } from "@/providers/AuthProvider";
import { AddProductProvider } from "@/providers/AddproductProvider";
import { Footer, WholeHeader } from "@/components/userComponents";
import { usePathname } from "next/navigation";
import { OrderProvider } from "@/providers/OrderProvider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathName = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <AuthProvider>
            <Userprovider>
              <OrderProvider>
                <CssBaseline>
                  <AddProductProvider>
                    {pathName.includes("dashboard") ? null : <WholeHeader />}
                    {children}
                    {pathName.includes("dashboard") ? null : <Footer />}
                  </AddProductProvider>
                </CssBaseline>
              </OrderProvider>
              <ToastContainer />
            </Userprovider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
